version: '3.8'

services:
  app:
    image: raynagah/evaluacion-parcial:latest
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=raynagah
      - DB_PASSWORD=raynagah123
      - DB_NAME=evaluacion_parcial2

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: raynagah
      MYSQL_DATABASE: evaluacion_parcial2
      MYSQL_USER: raynagah
      MYSQL_PASSWORD: raynagah123
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: raynagah