name: CI de Node.js con Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      security-events: write # Concede permiso para subir resultados de seguridad

    steps:
    - name: Checkout del código
      uses: actions/checkout@v4

    - name: Configurar Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Instalar dependencias
      run: npm install

    - name: Ejecutar Tests con Karma
      run: npx karma start karma.conf.js --single-run

    - name: Revisar código con ESLint
      run: npx eslint . --fix

    - name: Analizar dependencias con Snyk
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      run: npx snyk test || echo "Snyk ha encontrado vulnerabilidades, pero seguirá el flujo."

    - name: Análisis de código con SonarCloud
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Requerido por SonarCloud
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        npx sonar-scanner \
          -Dsonar.projectKey=x \
          -Dsonar.organization=x \
          -Dsonar.sources=./src \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}

    - name: Iniciar sesión en Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Construir y subir imagen a Docker Hub
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: raynagah/evaluacion-parcial:latest

